### ISSUE TITLE
Error en el index.php

### ISSUE THREAD

**Issue by AndreuGN** [AndreuGN/curso#3]
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec eros ex, pellentesque sed mauris posuere, elementum pellentesque nisi. Nam hendrerit lobortis volutpat. Aenean urna magna, dignissim nec condimentum a, vehicula eget turpis. Donec a elit ut nisl tincidunt scelerisque. Ut neque diam, placerat a sodales egestas, tincidunt consequat lacus. Donec interdum dictum feugiat. Interdum et malesuada fames ac ante ipsum primis in faucibus. Praesent mollis tempor lorem, vel vehicula arcu lobortis hendrerit. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Integer sodales mi quis tellus dignissim consequat.

**Comment by mperezma** [comment]
Es super intuitivo
